# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(default='', max_length=50)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
                ('dname', models.CharField(max_length=50)),
                ('dQlfy', models.CharField(max_length=100)),
                ('cSpec', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(default='', max_length=50)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(default='', max_length=50)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='labAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysistype', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('labId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.lab')),
            ],
        ),
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of birth ')),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('accType', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser'),
        ),
    ]
