# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('dQlfy', models.CharField(max_length=100)),
                ('cSpec', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateTimeField(verbose_name='Date of birth ')),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('accType', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser'),
        ),
    ]
