# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labanalysis',
            old_name='analysistype',
            new_name='type',
        ),
    ]
