# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appClinic', '0002_clinic_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('wtf', models.DateTimeField(verbose_name='working time from')),
                ('wtt', models.DateTimeField(verbose_name='workign time to')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('total_ranks', models.IntegerField(default=0)),
                ('users_rated', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='labAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('labId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinic.lab')),
            ],
        ),
    ]
