# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinic', '0004_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lab',
            name='logo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
