# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinic', '0006_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(verbose_name='Date of birth '),
        ),
    ]
